---
title: "stem-ghg-flux"
author: "EP"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
theme_set(theme_minimal())
library(arrow)
library(readr)
library(tidyr)
```

# Science questions

1. How much do tree stem GHG fluxes vary over the course of the year?
2. ...

# Read data

```{r read-data}
# Data file from the TEMPEST repository
message("Reading data...")
dat <- read_parquet("tempest_tree_ghg_fluxes.parquet")

message(nrow(dat), " rows and ", ncol(dat), " columns")
```

# Soil data

```{r soil-data}
# Read soil temperature and moisture data
files <- list.files(path = "L2_data/", pattern = "parquet$", full.names = TRUE)
lapply(files, read_parquet) %>% 
  bind_rows() %>% 
  # compute a 'Date' column...
  mutate(Date = as.Date(TIMESTAMP)) %>% 
  # ...and average variables for each date
  group_by(Site, Plot, Date, research_name) %>% 
  summarise(Value = mean(Value), .groups = "drop") %>% 
  # reshape 
  pivot_wider(names_from = "research_name", values_from = "Value", names_repair = "universal") ->
  soildat

# TODO: plot soil data
```


# Quick summary and visualization of data

```{r quick-look}
glimpse(dat)

# 1. Print summary
summary(dat)
# 2. ggplot(dat, ...)

```

# Join with species data

```{r sapflow-trees}
# 3. Drop existing species column from dat
# 4. Read in TEMPEST_Trees_Instruments.csv

tree_inventory <- read.csv("TEMPEST_Trees_Instruments.csv") %>% 
  select(Sapflux_ID, spp) # don't need these

#
dat %>%
  left_join(tree_inventory,
            # in dat the column is "ID", while in the tree inventory it's
            # "Sapflux_ID", so we tell left_join that these two columns 
            # correspond to each other 
            by = c("ID" = "Sapflux_ID"), 
            # this is optional but good 'defensive programming': we specify
            # that we expect a many-to-one relationship (i.e., there shouldn't
            # be multiple matches for a given sapflux tree!)
            relationship = "many-to-one") ->
        tree_dat

# To help readability, generate the common name from the species code
tree_dat %>%
  mutate(Species = case_when(
    spp == "ACRU" ~ "Red maple",
    spp == "LITU" ~ "Tulip poplar",
    spp == "FAGR" ~ "American beech"
  )) -> 
  tree_dat

# Make a nice summary table to check things
tree_dat %>% 
  # for each plot and species...
  group_by(Plot, Species) %>% 
  # ...count the number of distinct IDs...
  summarise(value = n_distinct(ID), .groups = "drop") %>% 
  # ...and then reshape so that plot names run across the top
  pivot_wider(names_from = "Plot") %>% 
  knitr::kable()
```

EVAN: from the table above we see a problem. What is it, and how do we deal with it?

# Plot annual cycle - raw data

```{r annual-cycle-raw}
# Filter out the TEMPEST flood measurements
tree_dat %>% 
  filter(Timepoint %in% c("(none)", "Pre-Treatment")) ->
  tree_dat_ac

message("Annual cycle dataset has ", nrow(tree_dat_ac), " rows and ",
        ncol(tree_dat_ac), " columns")

# EVAN:
# 1. What data frame do we want to use to plot?
# 2. This plots each tree as a separate color. How useful is this? What are alternatives?
ggplot(data = tree_dat, 
       mapping = aes(x = Date, y = CO2_lin_flux.estimate, color = Species))+
  geom_point() + # Add a layer of points
  labs(title = "Practice")  # Add labels and a title
```

# Summarize by ...?

The trees are _experimental units_ but what we're actually interested in is...

```{r annual-cycle-summary}

# EVAN: how do we want to summarize and then plot the annual cycle data?

```

